# The mixer id and secret. You can get one here https://mixer.com/lab/oauth.
# The secret is REQUIRED. MAKE SURE this config file is confidetntail.
mixer:
  id: ""
  secret: ""

# Players must be following one of the below mixer streamers to be able to join the server.
follow-users:
  - 45977218 # PhazorGDU
  - 65863356 # ItzJumble
  # - 68103774 # 45Ninjas

# Kick the user if they un-follow and would not be allowed back in later.
# WARNING: This feature is experimental.
kick-unfollow: true

# Database details.
database:
  jdbc: "jdbc:mysql://host:port/database"
  user: username
  password: password

# Customize these messages to fit your server/community. Details on variables at end of file.
messages:
  join-message: "§e::user:: (mixer ::mixer-user::) Joined the server.§r They are following ::follows::."
  # This message replaces the standard 'Those45Ninjas joined the game' message.
  # Varibles: ::user::, ::mixer-user::, and ::follows::

  start: |-
    Welcome ::user::. To join this server you must be following ::follows:: on mixer.com
    §ePlease enter your six digit code at §nhttps://mixer.com/go§r to join.§r

    §l§n::code::§r

    Re-join once you have finished.

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The message shown to the user when they are kicked for the first tme.
  # Or when the don't accept the permisions they are granting the OAuth.
  # Variables: ::code::, ::user::, ::expires:: and ::follows::
  
  code-un-used: |-
    §ePlease enter your six digit code at §nhttps://mixer.com/go§r to join.§r

    §l§n::code::§r

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The message shown when the user has not entered the six digit code.
  # Variables: ::code::, ::user::, ::expires:: and ::follows::

  code-expired: |-
    §eSorry your prevoius 6 digit code has expired.§r
    Please enter your §nNEW§r six digit code at §nhttps://mixer.com/go to join.

    §l§n::code::§r

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The message shown when the user's six digit code has expired.
  # Variables: ::code::, ::user::, ::expires:: and ::follows::

  code-forbidden: |-
    §eYou have §c§ndenied§r our server access to see who you are folloing on mixer.§r
    
    §nRe-join to try again.§r

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The message shown when the user's six digit code has expired.
  # Variables: ::code::, ::user::, ::expires:: and ::follows::
  
  not-following: |-
    §eYou must be following ::follows:: on mixer to join.§r

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The messge shown when the user is not following one of the streamers in the follow-users list.
  # Variables: ::user::, ::mixer-user:: and ::follows::
  
  fault: |-
    §eThere was an error while authorizing your account.§r

    §nError Details§r
    §c::exception::§r

    Having issues? Let us know on discord. §nhttps://discord.gg/MeGm6ZS§r
  # The message shown to the user when there was an error.
  # Variables avaliale: ::exception::

# Message variables are patterns that are replaced with data. For example all
# bits of text that match ::user:: is replaced with the username of the minecraft
# player.

# ::code::
#   The six digit code from mixer's shortcode system. that the user has to enter
#   into https://mixer.com/go
#   Example: 5 K J T L 4

# ::user::
#   The minecraft username of the user trying to join.
#   Example: Those45Ninjas

# ::mixer-user::
#   The username of the mixer account associated with the minecraft account.
#   Example: 45Ninjas

# ::follows::
#   The usernames (defined above) that the user must be following to join OR
#   the usernames that the user is following when they joinned the server.
#   Examples:
#     1 user long: PhazorGDU
#     2 users logn: PhazorGDU or ItzJumble
#     3 or more long: PazorGDU, ItzJumble or Those45Ninjas

# ::expires::
#   How many seconds until the shortcode expires.
#   Examples:
#     18 seconds
#     2 minutes
#     1 minute and 22 seconds

# ::exception::
#   A simple message describing the exception/error thrown. The terminal will show
#   more details.