mixer:
  id: ""
  secret: ""

database:
  jdbc: "jdbc:mysql://host:port/database"
  user: username
  password: password

messages:
  start: |-
    Welcome ::user::. To join this server you must be following PhazorGUD on mixer.com
    Please enter your six digit code at https://mixer.com/go to join.

    ::code::

    Having issues? Let us know on discord. https://discord.gg/MeGm6ZS
  code-un-used: |-
    Please enter your six digit code at https://mixer.com/go to join.

    ::code::

    Having issues? Let us know on discord. https://discord.gg/MeGm6ZS
  code-expired: |-
    Sorry your prevoius 6 digit code has expired.
    Please enter your six digit code at https://mixer.com/go to join.   

    ::code::

    Having issues? Let us know on discord. https://discord.gg/MeGm6ZS
  not-following: |-
    You must be following PhazorGDU on mixer to join.

    Having issues? Let us know on discord. https://discord.gg/MeGm6ZS    
  fault: |-
    Unfortuantley there was an error while authorizing your account.

    Error Details
    ::exception::

    Having issues? Let us know on discord. https://discord.gg/MeGm6ZS