mixer:
  id: ""
  secret: ""

database:
  jdbc: "jdbc:mysql://host:port/database"
  user: username
  password: password

link-message: |-
  Hello ::user::, Welcome to the GDU Minecraft server.
  To join this server you must be following PhazorGDU on Mixer.com.

  You need to go to https://mixer.com/go and enter the following six digit code.

  ::code::

  Having issues? Let us know on discord. https://discord.gg/MeGm6ZS

fault-message: |-
  Unfortuantley there was an error while authorizing your account.
  If this keeps happening tell us on discord https://discord.gg/MeGm6ZS

  Error Details
  ::exception::